# Generated by Django 3.2.5 on 2021-08-11 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Essay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('essayA', models.CharField(max_length=1000)),
                ('essayQ', models.CharField(max_length=1000)),
                ('name', models.CharField(max_length=10)),
            ],
        ),
    ]
