# Generated by Django 3.2.5 on 2021-08-12 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('write', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='essay',
            name='essayA',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='essay',
            name='essayQ',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='essay',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
