# Generated by Django 3.2.6 on 2021-08-12 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('write', '0002_auto_20210812_1107'),
    ]

    operations = [
        migrations.CreateModel(
            name='choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=5, max_digits=20)),
                ('group', models.TextField()),
                ('Q1', models.TextField()),
                ('A1', models.TextField()),
                ('Q2', models.TextField()),
                ('A2', models.TextField()),
                ('Q3', models.TextField()),
                ('A3', models.TextField()),
                ('Q4', models.TextField()),
                ('A4', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Essay',
        ),
    ]
