# Generated by Django 3.2.6 on 2021-08-16 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('write', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='lotto_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a', models.DecimalField(decimal_places=20, max_digits=20)),
                ('b', models.DecimalField(decimal_places=20, max_digits=20)),
                ('c', models.DecimalField(decimal_places=20, max_digits=20)),
                ('d', models.DecimalField(decimal_places=20, max_digits=20)),
                ('e', models.DecimalField(decimal_places=20, max_digits=20)),
                ('f', models.DecimalField(decimal_places=20, max_digits=20)),
                ('g', models.DecimalField(decimal_places=20, max_digits=20)),
                ('h', models.DecimalField(decimal_places=20, max_digits=20)),
                ('i', models.DecimalField(decimal_places=20, max_digits=20)),
                ('j', models.DecimalField(decimal_places=20, max_digits=20)),
                ('k', models.DecimalField(decimal_places=20, max_digits=20)),
                ('l', models.DecimalField(decimal_places=20, max_digits=20)),
                ('m', models.DecimalField(decimal_places=20, max_digits=20)),
            ],
        ),
    ]
