# Generated by Django 3.2.5 on 2021-08-18 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('write', '0002_lotto_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='alldata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('제목', models.TextField()),
                ('점수', models.DecimalField(decimal_places=5, max_digits=10)),
                ('답변', models.TextField()),
            ],
        ),
    ]
